#!/bin/bash
set -e

# Prerequisites Setup Script for Amazon Linux / EC2
# This script installs all required tools for DeliveryKick infrastructure

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}DeliveryKick Prerequisites Setup${NC}"
echo -e "${BLUE}Amazon Linux / EC2${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Detect OS
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$NAME
    VER=$VERSION_ID
    echo -e "Detected OS: ${YELLOW}$OS $VER${NC}"
else
    echo -e "${RED}Cannot detect OS. This script is for Amazon Linux.${NC}"
    exit 1
fi

# Update system
echo ""
echo -e "${YELLOW}Step 1: Updating system packages...${NC}"
if [[ "$OS" == *"Amazon Linux 2023"* ]]; then
    sudo dnf update -y
elif [[ "$OS" == *"Amazon Linux"* ]]; then
    sudo yum update -y
else
    echo -e "${YELLOW}Warning: Untested OS. Continuing anyway...${NC}"
    sudo yum update -y
fi
echo -e "${GREEN}✓ System updated${NC}"

# Install basic tools
echo ""
echo -e "${YELLOW}Step 2: Installing basic tools...${NC}"
if [[ "$OS" == *"Amazon Linux 2023"* ]]; then
    sudo dnf install -y git unzip wget jq || true
    # curl is usually pre-installed, skip if conflict
else
    sudo yum install -y git unzip wget jq || true
fi
echo -e "${GREEN}✓ Basic tools installed${NC}"

# Check AWS CLI
echo ""
echo -e "${YELLOW}Step 3: Checking AWS CLI...${NC}"
if command -v aws &> /dev/null; then
    AWS_VERSION=$(aws --version 2>&1 | cut -d/ -f2 | cut -d' ' -f1)
    echo -e "${GREEN}✓ AWS CLI already installed (version $AWS_VERSION)${NC}"
else
    echo "Installing AWS CLI v2..."
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip -q awscliv2.zip
    sudo ./aws/install
    rm -rf aws awscliv2.zip
    echo -e "${GREEN}✓ AWS CLI installed${NC}"
fi

# Install Terraform
echo ""
echo -e "${YELLOW}Step 4: Installing Terraform...${NC}"
TERRAFORM_VERSION="1.6.6"

if command -v terraform &> /dev/null; then
    CURRENT_VERSION=$(terraform version -json | jq -r .terraform_version)
    echo -e "Terraform already installed (version $CURRENT_VERSION)"
    read -p "Do you want to reinstall version $TERRAFORM_VERSION? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Skipping Terraform installation"
        SKIP_TF=true
    fi
fi

if [ -z "$SKIP_TF" ]; then
    wget -q https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
    unzip -q terraform_${TERRAFORM_VERSION}_linux_amd64.zip
    sudo mv terraform /usr/local/bin/
    rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip
    echo -e "${GREEN}✓ Terraform ${TERRAFORM_VERSION} installed${NC}"
fi

# Verify Terraform
terraform --version

# Install Docker
echo ""
echo -e "${YELLOW}Step 5: Installing Docker...${NC}"
if command -v docker &> /dev/null; then
    echo -e "${GREEN}✓ Docker already installed${NC}"
else
    if [[ "$OS" == *"Amazon Linux 2023"* ]]; then
        sudo dnf install -y docker
    else
        sudo yum install -y docker
    fi

    # Start and enable Docker
    sudo systemctl start docker
    sudo systemctl enable docker

    # Add current user to docker group
    sudo usermod -aG docker $USER

    echo -e "${GREEN}✓ Docker installed${NC}"
    echo -e "${YELLOW}Note: You may need to logout and login again for docker group to take effect${NC}"
    echo -e "Or run: ${BLUE}newgrp docker${NC}"
fi

# Install PostgreSQL client
echo ""
echo -e "${YELLOW}Step 6: Installing PostgreSQL client...${NC}"
if command -v psql &> /dev/null; then
    echo -e "${GREEN}✓ PostgreSQL client already installed${NC}"
else
    if [[ "$OS" == *"Amazon Linux 2023"* ]]; then
        sudo dnf install -y postgresql15
    elif [[ "$OS" == *"Amazon Linux 2"* ]]; then
        sudo amazon-linux-extras enable postgresql14 2>/dev/null || true
        sudo yum install -y postgresql
    else
        sudo yum install -y postgresql
    fi
    echo -e "${GREEN}✓ PostgreSQL client installed${NC}"
fi

# Create environment file
echo ""
echo -e "${YELLOW}Step 7: Creating environment configuration...${NC}"

cat > ~/.deliverykick-env << 'EOF'
# DeliveryKick Environment Configuration
# Generated by setup-prerequisites-linux.sh

# AWS Configuration
export AWS_REGION=us-east-1
export AWS_DEFAULT_REGION=us-east-1

# Get AWS Account ID dynamically (requires AWS CLI to be configured)
if command -v aws &> /dev/null && aws sts get-caller-identity &> /dev/null; then
    export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
fi

# Aurora Configuration
export AURORA_CLUSTER_ID=deliverykick-prod-cluster
export AURORA_MASTER_USER=postgres

# Terraform
export TF_VAR_aws_region=us-east-1

# Add /usr/local/bin to PATH if not already there
if [[ ":$PATH:" != *":/usr/local/bin:"* ]]; then
    export PATH=$PATH:/usr/local/bin
fi

# Useful aliases
alias dk-logs-ordering='aws logs tail /ecs/deliverykick-prod/ordering --follow'
alias dk-logs-restaurant='aws logs tail /ecs/deliverykick-prod/restaurant --follow'
alias dk-status='aws ecs describe-services --cluster deliverykick-prod-cluster --services deliverykick-prod-ordering deliverykick-prod-restaurant --query "services[].[serviceName,status,runningCount,desiredCount]" --output table'
alias dk-tf='cd ~/deliverykick-infrastructure/terraform/environments/prod'
EOF

# Add to .bashrc if not already there
if ! grep -q "source ~/.deliverykick-env" ~/.bashrc 2>/dev/null; then
    echo "" >> ~/.bashrc
    echo "# DeliveryKick environment" >> ~/.bashrc
    echo "source ~/.deliverykick-env" >> ~/.bashrc
fi

echo -e "${GREEN}✓ Environment configuration created${NC}"

# Summary
echo ""
echo -e "${BLUE}========================================${NC}"
echo -e "${GREEN}Installation Complete!${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo -e "${YELLOW}Installed tools:${NC}"
echo "  ✓ AWS CLI:        $(aws --version 2>&1 | cut -d' ' -f1)"
echo "  ✓ Terraform:      $(terraform version -json | jq -r .terraform_version)"
echo "  ✓ Docker:         $(docker --version | cut -d' ' -f3 | tr -d ',')"
echo "  ✓ PostgreSQL:     $(psql --version | cut -d' ' -f3)"
echo "  ✓ Git:            $(git --version | cut -d' ' -f3)"
echo "  ✓ jq:             $(jq --version | cut -d'-' -f2)"
echo ""

# Check AWS configuration
echo -e "${YELLOW}AWS Configuration:${NC}"
if aws sts get-caller-identity &> /dev/null; then
    ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
    USER_ARN=$(aws sts get-caller-identity --query Arn --output text)
    REGION=$(aws configure get region)
    echo -e "  ✓ Account ID:     $ACCOUNT_ID"
    echo -e "  ✓ User/Role:      $USER_ARN"
    echo -e "  ✓ Region:         $REGION"
else
    echo -e "  ${RED}✗ AWS CLI not configured${NC}"
    echo -e "  Run: ${BLUE}aws configure${NC}"
fi

echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo ""
echo -e "1. Configure AWS CLI (if not done):"
echo -e "   ${BLUE}aws configure${NC}"
echo ""
echo -e "2. Load environment variables:"
echo -e "   ${BLUE}source ~/.deliverykick-env${NC}"
echo ""
echo -e "3. If you installed Docker, logout/login or run:"
echo -e "   ${BLUE}newgrp docker${NC}"
echo ""
echo -e "4. Follow the deployment guide:"
echo -e "   ${BLUE}cat docs/SETUP_AMAZON_LINUX.md${NC}"
echo ""
echo -e "${GREEN}Ready to deploy DeliveryKick! 🚀${NC}"
echo ""
